apiVersion: apps/v1
kind: Deployment
metadata:
  name: pointsystem
  labels:
    app: pointsystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pointsystem
  template:
    metadata:
      labels:
        app: pointsystem
    spec:
      containers:
        - name: pointsystem
          image: "a0717.azurecr.io/pointsystem3:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
